# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_to_model1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.moDEl1')),
            ],
        ),
    ]
